### ISSUE TITLE
Add cyrillic font subset in Russian translation

### ISSUE THREAD

**Issue by Zverik** [harry-wood/osmblog-wp-theme#1]
http://blog.openstreetmap.org/?lang=ru is missing cyrillic subsets for Open Sans web font declaration. They should be included by translating `no-subset` to `cyrillic` (see [this code fragment](https://github.com/harry-wood/osmblog-wp-theme/blob/master/functions.php#L118)). It seems the current translation doesn't do so. And there are no .po/.mo files on github, so it falls on the person with access to the server.

**Comment by Zverik** [comment]
The added Russian translation did not solve the problem. Please add [this one](http://i18n.svn.wordpress.org/ru_RU/trunk/messages/twentytwelve/) (this is theme translation, not WP).

**Comment by harry-wood** [comment]
Alright then...  https://github.com/harry-wood/osmblog-wp-theme/commit/ef9c7fd985e1554aa36417c0b4b000d39dc4e6f9
