### ISSUE TITLE
osm favicon

### ISSUE THREAD

**Issue by harry-wood** [harry-wood/osmblog-wp-theme#11]
Didn't blog.openstreetmap.org used to have the OSM favicon? (same as openstreetmap.org)

It's showing the wordpress "W" favicon these days.

Replace it with the same osm favicon (This issue is not about discussing what the favicon should be. Just that it shouldn't be the wordpress "W")

**Comment by Firefishy** [comment]
I think the favicon is now managed from within wordpress settings.

**Comment by harry-wood** [comment]
Ah OK yeah. under "[customize](https://blog.openstreetmap.org/wp-admin/customize.php)" -> "site identity". I've set the favicon!
