### ISSUE TITLE
Should we move the repo to osmfoundation organisation?

### ISSUE THREAD

**Issue by nebulon42** [harry-wood/osmblog-wp-theme#4]
Just that everything is together and editable by the necessary persons.
I'm not having a strong opinion on that but I think it would be a good thing.

**Comment by Firefishy** [comment]
@harry-wood OK if we arrange this?

**Comment by harry-wood** [comment]
Sure.

Although while we're thinking about that...  we're based on a very old theme version ("twentytwelve" which dates from ... 2012), it might solve some things if we re-do our theme based off something newer. Also with the design I originally tried to mimic the look of the [diaries](https://www.openstreetmap.org/diary), but then they changed a bit, so re-doing that whole thing wouldn't be such a bad idea. I can volunteer to do this work (again) if you like, or if someone else is keen... 

So with this in mind it might make sense to name this "osmblog-wp-theme-original" or something, and then we drop a new theme in fresh repo.

**Comment by Firefishy** [comment]
@harry-wood for the moment could you please make me a repo contributor under settings?

**Comment by pnorman** [comment]
Did @harry-wood do this or is it waiting on @Firefishy?

**Comment by harry-wood** [comment]
Which bit? Re-doing our theme based off something newer, is not something I have got around to yet. But maybe some time soon.

**Comment by pnorman** [comment]
> Which bit?

Making grant a repo contributor

**Comment by Firefishy** [comment]
@harry-wood I think you might be able to move/transfer the repo yourself. 
Use the transfer function at the bottom of: https://github.com/harry-wood/osmblog-wp-theme/settings
Destination: https://github.com/osmfoundation/osmblog-wp-theme/

**Comment by Firefishy** [comment]
Thank you.
